# Generated by Django 3.2 on 2023-01-05 00:59

import core.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quote', models.TextField(verbose_name='Citação')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('author_link', models.CharField(max_length=200, verbose_name='Link do Autor')),
                ('born', models.CharField(max_length=100, verbose_name='Nascimento')),
                ('place', models.CharField(max_length=100, verbose_name='Local')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('link', models.URLField(verbose_name='link')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.record', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
