# Generated by Django 3.2 on 2023-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterField(
            model_name='record',
            name='pag',
            field=models.TextField(verbose_name='Page'),
        ),
    ]
